version: '3'

services:

#  db:
#    image: mysql
#    command: --default-authentication-plugin=mysql_native_password
#    restart: always
#    #volumes:
#    #  - ./docker/mysql/config.cnf:/etc/mysql/conf.d/config.cnf
#    ports:
#      - 3306:3306
#    environment:
#      MYSQL_ROOT_PASSWORD: root
#      MYSQL_DATABASE: db_name
#      MYSQL_USER: db_user
#      MYSQL_PASSWORD: db_pass
  
  swoole:
    image: phpswoole/swoole
    ports:
      - '9501:9501'
    volumes:
      - ./:/var/www
    env_file:
    - .env
    
#    depends_on:
#      - db
#    links: 
#      - db:db
  
#  apache:
#    build: 
#      context: .
#      dockerfile: Dockerfile
#      args:
#        buildno: 2
#    volumes:
#      - ./:/var/www/html
#    ports:
#      - '8000:80'
#    depends_on:
#      - db
#    links: 
#      - db:db
#    environment:
#      
#      MYSQL_HOST: db
#      MYSQL_ROOT_PASSWORD: root
#      MYSQL_DATABASE: db_name
#      MYSQL_USER: db_user
#      MYSQL_PASSWORD: db_pass

#  adminer:
#    image: adminer
#    restart: always
#    depends_on:
#      - db
#    links: 
#      - db:db
#    ports:
#      - 8088:8080