apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: baseline-graphql-siler
  description: The Baseline API
  tags:
    - baseline
    - graphql
spec:
  type: openapi
  lifecycle: experimental
  owner: borges@example.com
  definition: |
    openapi: "3.0.0"
    info:
      version: 1.0.0
      title: Swagger Baseline
      license:
        name: MIT
    servers:
      - url: http://baseline.swagger.io/v1
    paths:
      /endpoint:
        get:
          summary: List all
          operationId: listAll
          tags:
            - endpoints
          parameters:
            - name: limit
              in: query
              description: How many items to return at one time (max 100)
              required: false
              schema:
                type: integer
                format: int32
          responses:
            '200':
              description: A paged array of pets
              headers:
                x-next:
                  description: A link to the next page of responses
                  schema:
                    type: string
              content:
                application/json:
                  schema:
                    $ref: "#/components/schemas/Pets"
            default:
              description: unexpected error
              content:
                application/json:
                  schema:
                    $ref: "#/components/schemas/Error"
    components:
      schemas:
        Pet:
          type: object
          required:
            - id
            - name
          properties:
            id:
              type: integer
              format: int64
            name:
              type: string
            tag:
              type: string
        Pets:
          type: array
          items:
            $ref: "#/components/schemas/Pet"
        Error:
          type: object
          required:
            - code
            - message
          properties:
            code:
              type: integer
              format: int32
            message:
              type: string
